// flow-typed signature: 7784adda5283ecf3f5b67a22cdd1b374
// flow-typed version: <<STUB>>/@workpop/graphql-resolver-utils_v^0.2.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@workpop/graphql-resolver-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@workpop/graphql-resolver-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@workpop/graphql-resolver-utils/lib/createResolvers' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/lib/index' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/lib/sanitizeArgs' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/lib/secureResolvers' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/src/createResolvers' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/src/index' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/src/sanitizeArgs' {
  declare module.exports: any;
}

declare module '@workpop/graphql-resolver-utils/src/secureResolvers' {
  declare module.exports: any;
}

// Filename aliases
declare module '@workpop/graphql-resolver-utils/lib/createResolvers.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/lib/createResolvers'>;
}
declare module '@workpop/graphql-resolver-utils/lib/index.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/lib/index'>;
}
declare module '@workpop/graphql-resolver-utils/lib/sanitizeArgs.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/lib/sanitizeArgs'>;
}
declare module '@workpop/graphql-resolver-utils/lib/secureResolvers.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/lib/secureResolvers'>;
}
declare module '@workpop/graphql-resolver-utils/src/createResolvers.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/src/createResolvers'>;
}
declare module '@workpop/graphql-resolver-utils/src/index.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/src/index'>;
}
declare module '@workpop/graphql-resolver-utils/src/sanitizeArgs.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/src/sanitizeArgs'>;
}
declare module '@workpop/graphql-resolver-utils/src/secureResolvers.js' {
  declare module.exports: $Exports<'@workpop/graphql-resolver-utils/src/secureResolvers'>;
}
