// flow-typed signature: 6d37dfb3264c8610d30ce9eb65918a45
// flow-typed version: <<STUB>>/@workpop/simple-logger_v^1.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@workpop/simple-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@workpop/simple-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@workpop/simple-logger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@workpop/simple-logger/lib/index.js' {
  declare module.exports: $Exports<'@workpop/simple-logger/lib/index'>;
}
